version: '2'
services:
  db:
    image: postgres:17
    user: root
    environment:
      - POSTGRES_USER=haui
      - POSTGRES_PASSWORD=haui-psw
      - POSTGRES_DB=postgres
    restart: always
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo18:
    image: odoo:18
    user: root
    depends_on:
      - db
    ports:
      - "3000:8069"
      - "3001:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=haui
      - PASSWORD=haui-psw
      - PIP_BREAK_SYSTEM_PACKAGES=1
    restart: always
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo